### ISSUE TITLE
add "delete all" button on popup UI, to delete all records

### ISSUE THREAD

**Issue by architec** [arch-org/mistake#44]
@a6you

**Comment by a6you** [comment]
I'll try this

**Comment by architec** [comment]
Please use "DeleteSweep" icon from Material UI, and place this icon on the top right corner, beside the header

**Comment by architec** [comment]
@a6you

**Comment by a6you** [comment]
Will try to get to this over the weekend

**Comment by architec** [comment]
@a6you  Please do a git pull, and use the button currently in place for the "delete all" button. Thanks!
