### ISSUE TITLE
add problem list website into footer

### ISSUE THREAD

**Issue by architec** [arch-org/mistake#58]
https://www.programcreek.com/2012/11/top-10-algorithms-for-coding-interview/
and this
https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions

import AccountTreeIcon from '@mui/icons-material/AccountTree';

**Comment by Reedham20** [comment]
Hey, I am new to open source and I think I can start here, can you please explain where the changes are to be made.

**Comment by architec** [comment]
Yes, you will need to add two more icons similar to the one already there, with AccountTreeIcon from Material Icon. It is ok to let all 3 icons be centered in the middle.

Good Starting Point: https://github.com/arch-org/mistake/blob/cc013b2c4ad592e017a546b80294599fda5f4b89/src/pages/Popup/Popup.jsx#L162

**Comment by Reedham20** [comment]
Thanks for the help.. I will try and make a PR as soon as possible

**Comment by Reedham20** [comment]
Should I use the same Icon for both links?

**Comment by architec** [comment]
good job!
